server:
  port: 8081

  spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/miniproject_jdbl?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root



  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true



